name: expense_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.0.0
  ionicons: ^0.2.2
  material_symbols_icons: ^4.2789.0
  flutter_colorpicker: ^1.1.0
  dashed_circular_progress_bar: ^0.0.6
  flutter_iconpicker: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Indented with 2 spaces

  fonts:
    - family: Pacifico  # Indented with 2 spaces
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
